apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.account}}.dkr.ecr.eu-west-1.amazonaws.com/{{ .Values.namespace }}/{{ .Chart.Name }}:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
